In [1]:
import numpy as np

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).


In [10]:
N = 10 #число элементов
my_first_array = np.arange(N, -1, -1)
my_first_array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [30]:
N = 3 #число элементов
my_matrix =  np.diag(np.arange(N, -1, -1), k=0)
ss = sum(np.diagonal(my_matrix))
print(my_matrix, ss)

[[3 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [0 0 0 0]] 6


# Задание 3

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3


In [24]:
from numpy import linalg as la

a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) #матрица системы
b = np.array([4, 12, -3]) #свободные коэффициенты

x = la.solve(a, b) #вектор неизвестныx

#Проверка решения и просто использовать метод дот
b_check = np.dot(a, x)
print(x, b_check)

[ 0.46666667  3.84444444 -5.55555556] [ 4. 12. -3.]


# Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [25]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [26]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [36]:
close_matrix = [np.dot(user, next_user_stats)/la.norm(user)/la.norm(next_user_stats) for user in users_stats]

ind = close_matrix.index(max(close_matrix))

print(f'ближайший пользователь к {next_user_stats} это {users_stats[ind]}')

ближайший пользователь к [0 1 2 0 0 0] это [0 1 1 0 0 0]
